### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by Tocontinueox12** [muxiaozi/LiveCamera#1]
请问这个Qt运行的版本和SDK时多少？

**Comment by muxiaozi** [comment]
QT5即可(Qt5.11.2 + VS2019）亲测成功编译运行，但是用QtCreator却出现了一些问题，原因未知

**Comment by Tocontinueox12** [comment]
我先使用了vs2017 +Qt  5.11.1，导入项目时，遇到头文件无法导入的问题，解决后，报错很多。我现在需要你的帮助，如果有意，可加wx ljx142578
